/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankRouteImport } from './routes/bank'
import { Route as DrillRouteImport } from './routes/drill'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as MapRouteImport } from './routes/map'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as ModulesIndexRouteImport } from './routes/modules/index'
import { Route as ModulesModuleIdRouteImport } from './routes/modules/$moduleId'
import { Route as V2IndexRouteImport } from './routes/v2/index'
import { Route as V2BankRouteImport } from './routes/v2/bank'
import { Route as V2ExamRouteImport } from './routes/v2/exam'
import { Route as V2TreeRouteImport } from './routes/v2/tree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const DrillRoute = DrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdRoute = ModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const V2IndexRoute = V2IndexRouteImport.update({
  id: '/v2/',
  path: '/v2/',
  getParentRoute: () => rootRouteImport,
} as any)
const V2BankRoute = V2BankRouteImport.update({
  id: '/v2/bank',
  path: '/v2/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const V2ExamRoute = V2ExamRouteImport.update({
  id: '/v2/exam',
  path: '/v2/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const V2TreeRoute = V2TreeRouteImport.update({
  id: '/v2/tree',
  path: '/v2/tree',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/drill': typeof DrillRoute
  '/exam': typeof ExamRoute
  '/map': typeof MapRoute
  '/tree': typeof TreeRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/v2/bank': typeof V2BankRoute
  '/v2/exam': typeof V2ExamRoute
  '/v2/tree': typeof V2TreeRoute
  '/modules/': typeof ModulesIndexRoute
  '/v2/': typeof V2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/drill': typeof DrillRoute
  '/exam': typeof ExamRoute
  '/map': typeof MapRoute
  '/tree': typeof TreeRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/v2/bank': typeof V2BankRoute
  '/v2/exam': typeof V2ExamRoute
  '/v2/tree': typeof V2TreeRoute
  '/modules': typeof ModulesIndexRoute
  '/v2': typeof V2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/drill': typeof DrillRoute
  '/exam': typeof ExamRoute
  '/map': typeof MapRoute
  '/tree': typeof TreeRoute
  '/modules/$moduleId': typeof ModulesModuleIdRoute
  '/v2/bank': typeof V2BankRoute
  '/v2/exam': typeof V2ExamRoute
  '/v2/tree': typeof V2TreeRoute
  '/modules/': typeof ModulesIndexRoute
  '/v2/': typeof V2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank'
    | '/drill'
    | '/exam'
    | '/map'
    | '/tree'
    | '/modules/$moduleId'
    | '/v2/bank'
    | '/v2/exam'
    | '/v2/tree'
    | '/modules/'
    | '/v2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank'
    | '/drill'
    | '/exam'
    | '/map'
    | '/tree'
    | '/modules/$moduleId'
    | '/v2/bank'
    | '/v2/exam'
    | '/v2/tree'
    | '/modules'
    | '/v2'
  id:
    | '__root__'
    | '/'
    | '/bank'
    | '/drill'
    | '/exam'
    | '/map'
    | '/tree'
    | '/modules/$moduleId'
    | '/v2/bank'
    | '/v2/exam'
    | '/v2/tree'
    | '/modules/'
    | '/v2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
  DrillRoute: typeof DrillRoute
  ExamRoute: typeof ExamRoute
  MapRoute: typeof MapRoute
  TreeRoute: typeof TreeRoute
  ModulesModuleIdRoute: typeof ModulesModuleIdRoute
  V2BankRoute: typeof V2BankRoute
  V2ExamRoute: typeof V2ExamRoute
  V2TreeRoute: typeof V2TreeRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  V2IndexRoute: typeof V2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drill': {
      id: '/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof DrillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId': {
      id: '/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/modules/$moduleId'
      preLoaderRoute: typeof ModulesModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/': {
      id: '/v2/'
      path: '/v2'
      fullPath: '/v2/'
      preLoaderRoute: typeof V2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/bank': {
      id: '/v2/bank'
      path: '/v2/bank'
      fullPath: '/v2/bank'
      preLoaderRoute: typeof V2BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/exam': {
      id: '/v2/exam'
      path: '/v2/exam'
      fullPath: '/v2/exam'
      preLoaderRoute: typeof V2ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v2/tree': {
      id: '/v2/tree'
      path: '/v2/tree'
      fullPath: '/v2/tree'
      preLoaderRoute: typeof V2TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
  DrillRoute: DrillRoute,
  ExamRoute: ExamRoute,
  MapRoute: MapRoute,
  TreeRoute: TreeRoute,
  ModulesModuleIdRoute: ModulesModuleIdRoute,
  V2BankRoute: V2BankRoute,
  V2ExamRoute: V2ExamRoute,
  V2TreeRoute: V2TreeRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  V2IndexRoute: V2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
